### ISSUE TITLE
Translations and a thought on management

### ISSUE THREAD

**Issue by mortommy** [openhab/openhab-mycroft#1]
_From @ThomDietrich on September 6, 2017 11:42_

Heyho!
Soon users might want to add other languages to your skill. It will be hard to keep all command options in sync between the different language files.

There are special services that help manage translations. Some of those can be integrated with GitHub. You should have a look! Just yesterday integration of a new service was announced through the GitHub blog: https://github.com/blog/2427-extend-your-workflow-with-these-new-marketplace-apps -> "Localization"

Also:
* https://github.com/marketplace/category/localization
* https://github.com/works-with/category/localization

_Copied from original issue: mortommy/mycroft-skill-openhab#9_

**Comment by mortommy** [comment]
Thank you. I'll have a look.

**Comment by ThomDietrich** [comment]
Hey @mortommy, with @piretro999 starting to add a new language, you should realy think about Translation management. https://github.com/marketplace/crowdin Seems to be the better choice.

**Comment by mortommy** [comment]
Yes, I omitted so far this part. I'll read it.
Thank you.

**Comment by mortommy** [comment]
Unfortunately at the moment they don't support .dialog, .voc, .rx files, there's a list of [supported formats](https://support.crowdin.com/supported-formats/). We can ask for a new format [here](https://crowdin.uservoice.com/forums/31787-collaborative-translation-tool).

**Comment by mortommy** [comment]
also the [other one](https://github.com/marketplace/gitlocalize) in the market place doesn't support our files format.

**Comment by ThomDietrich** [comment]
Supported formats are just those crowdin specifically knows. In general they support translations for all text-based files. Just tested it and it works just fine:

![grafik](https://user-images.githubusercontent.com/2870104/32740405-21e93ce0-c8a3-11e7-8927-b2ced1f95288.png)

![grafik](https://user-images.githubusercontent.com/2870104/32740483-6695faea-c8a3-11e7-9466-b6d94ca7c9d7.png)



Result: https://github.com/ThomDietrich/skill-openhab/pull/1

**Comment by mortommy** [comment]
Ok. I was looking at GitLocalize and doen't find even the files, I'll also test Crowdin.

**Comment by mortommy** [comment]
Hi @ThomDietrich ,
I had the opportunity to make some test and is working. I have doubts about the workflow. Users will rise PR via github as @piretro999 did, how they can go through Crowdin?

**Comment by ThomDietrich** [comment]
Where exactly? I can't see it: https://crowdin.com/projects?q=openhab#advanced-search
You'd basically just reference the project URL in the README, something like "If you want to help add translations, please go to ...". You could also add README files to the three subfolders. Whatever you feel will be the easiest to make users aware.
As soon as someone adds translations via crowdin, crowdin will open a PR in their name. It's a very comfortable process.

**Comment by mortommy** [comment]
Hi @ThomDietrich ,
sorry it has been a long time since your help. I just created the [project](https://crwd.in/openhab-mycroft) in Crowdin. It's my first project, could you have a check if it is ok?
Thank you.
