### ISSUE TITLE
Feature request: Get status of Window/Door Contacts

### ISSUE THREAD

**Issue by mortommy** [openhab/openhab-mycroft#2]
_From @Andirs55 on September 7, 2017 10:20_

Hey it would be cool if one could ask Mycroft if a certain window or door is opened or closed.

E.g.:

"Hey Mycroft, is the Bedroom window open?"
"Hey Mycroft, is the Bedroom window opened?"
"Hey Mycroft, is the Bedroom window closed?"

Thanks :)

_Copied from original issue: mortommy/mycroft-skill-openhab#11_

**Comment by mortommy** [comment]
Hi,
a similar command is already available for the CurrentTemperature, CurrentHumidity and TargetTemperature tagged items, but the voice command is:

- *"Hey Mycroft, what's Bedroom humidity?"*

so it could be:

- *"Hey Mycroft, what's Bedroom window status?"* 

using this, make available this feature should be easy, but anyway probably has sense only for Switchable tagged item.

What do you think?

**Comment by andiwirs** [comment]
If this is easy for you to implement, i am totally fine with it :)
