### ISSUE TITLE
README.md referencing mortommy/mycroft-skill-openhab repository instead of openhab

### ISSUE THREAD

**Issue by Empor-co** [openhab/openhab-mycroft#23]
Hi openhab-Team,

the README.md is still referencing 
`git clone https://github.com/mortommy/mycroft-skill-openhab skill-openhab `
instead of 
`git clone https://github.com/openhab/openhab-mycroft.git skill-openhab`

this leads to cloning version 1.0 instead of the current 1.1

Best regards,

Empor-co

**Comment by mortommy** [comment]
oops, you are right.
