### ISSUE TITLE
Percent commands

### ISSUE THREAD

**Issue by mortommy** [openhab/openhab-mycroft#3]
_From @ThomDietrich on September 5, 2017 13:23_

Is the example wrong?

*"Hey Mycroft, set Diningroom to 50"* -> *"Hey Mycroft, set Diningroom to 50 percent"*

_Copied from original issue: mortommy/mycroft-skill-openhab#6_

**Comment by mortommy** [comment]
Looking at the code is not wrong. I didn't test it but it should work anyway.
Should be "percent" mandatory?

**Comment by mortommy** [comment]
_From @ThomDietrich on September 5, 2017 13:39_

Maybe you can test this in your setup?

Should it be mandatory? Well the user should be encouraged to form natural sentences, right? Hence there should be a percent and now that I think about it a "light" in the sentence.

Because of that I'd also check if commands like "set Diningroom light to half the intensity" is possible.

**Comment by mortommy** [comment]
_From @ThomDietrich on September 5, 2017 14:14_

https://github.com/mortommy/mycroft-skill-openhab/blob/master/regex/en-us/dimmer_command.rx

Now I actually get your comment. You as the skill developer are in charge to define the structure of the commands understood by the skill. That is just great! I will have to do some testing!!

**Comment by mortommy** [comment]
Hi,
changed the regex expression to have the word "percent" optional:
f.i
`(set) (?P<Item>.*) (to) (?P<BrigthPercentage>\d*)(?: percent)?`

so both the commands:
- *"Hey Mycroft, set Diningroom to 50 percent"*
- *"Hey Mycroft, set Diningroom to 50"*
work.

Regarding the other request 
"commands like set Diningroom light to half the intensity"

 I have to create a new type of command, at the moment is not working. Should be created a new Issue?

**Comment by ThomDietrich** [comment]
Hey, thanks for the addition! 
I'm not feeling strongly about the second. I'd need to get a feeling for the system first.
You may close this one for now. Thanks

**Comment by mortommy** [comment]
Great.
