### ISSUE TITLE
Bright and Brighten

### ISSUE THREAD

**Issue by stefmorp** [openhab/openhab-mycroft#33]
Hi, and thanks for the great job!

I wanted to point out a small bug that prevents the skill to work. DimmerStatusKeyword says:
set
dim
bright

but dimmer_command says:
(dim|brighten) (?P<Item>.*?)\s*(?: by )?(?P<BrigthPercentage>\d*)?(?: percent)?$

As you can see, one says bright the other brighten. This is why dim works and bright does not. By the way brighten works very poorly (90% of the times it reads brighton) so in my installation I manually corrected both to bright.
Hope this helps!
Stefano

**Comment by mortommy** [comment]
Hi,
could you make a PR with your correction? Otherwise no worries, I'll fix it when I have time.
Thank you.

**Comment by stefmorp** [comment]
Hi,
thanks for your prompt reply. Pardon my ignorance, what is a PR and how do I make one? I'm happy to do it and to learn something new.
Ciao
Stefano

**Comment by mortommy** [comment]
Thank you your report.

**Comment by mortommy** [comment]
Fixed. Thank you.
