### ISSUE TITLE
Requesting Debug help - mycroft names don't match openHab names

### ISSUE THREAD

**Issue by bgarr33434** [openhab/openhab-mycroft#43]
so with PaperUI, just to single out a one device, Desk Light works fine.  It is LIFX and I can turn it on/off or dim with PaperUI.

When I ask Mycroft to list openHab devices, the list comes back like this
Lights: brightness, brightness, color, brightness, brightness
which has the right number of devices, but Mycroft never gets a hit trying to go through the REST api at my local openHab

**Comment by mortommy** [comment]
Hi,
if Mycroft is able to list the devices it is able to go via openHAB REST API, however in the list you get there's no the item "Desk Light" so something is wrong in the openHAB items definition. As reported in the [documentation](https://www.openhab.org/docs/ecosystem/mycroft/#openhab-item-configuration) matching of voice commands to Items happens based on the Item label, so you have to label your item as "Desk Light". If you can't fix the issue please post the item definition.

**Comment by mortommy** [comment]
Hi,
did you have the opportunity to check the items definition?

**Comment by bgarr33434** [comment]
I did, but I don't understand the syntax and WHERE I do this? Am I supposed to create a new config file and define the mycroft label = openHAB label?  I get the feeling openHAB can be very powerful.  I just need a really simple one line example for a Lifx light called Desk Light on the LIFX network and on OpenHAB.  If I can get one to work then I can get everything else done, and maybe even define my NEST thermostat by myself.  It's just the hurdle to understand in extremely simple terms how I start.  Thanks.

**Comment by mortommy** [comment]
Hi,
yes, it is just a matter of configuration. Have a look [here](https://www.openhab.org/docs/ecosystem/mycroft/#general-configuration-instructions) where you can find some examples; anyway you can always ask for help in the community [website](https://community.openhab.org/).
I'm going to close the issue.
thank you.
