### ISSUE TITLE
mycroft skill is listed as "under construction"

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-mycroft#47]
Just saw https://github.com/MycroftAI/mycroft-skills/blob/master/README.md#community-contributed-skill-list and noticed that openHAB is marked as "still being developed and not ready for general use (for reference/collaboration)".

@mortommy Do you know what needs to be done to get it fully approved?

**Comment by mortommy** [comment]
Hi,
I'm not sure that is still the skills list page, from the main page the list of skills available is [here](https://mycroftai.github.io/mycroft-skills/).

**Comment by kaikreuzer** [comment]
Hm, their main page now displays the branch 18.02 by default, while I referred to the version in the master branch.
They seem to have some weird branch management, if master isn't the lastest version of the code...

**Comment by kaikreuzer** [comment]
But, probably no need to become active then, thanks!
