### ISSUE TITLE
openhab mycroft installation

### ISSUE THREAD

**Issue by montanaman2017** [openhab/openhab-mycroft#50]
I'd like to know if there is a video demonstrating the install and of this working?  I'm asking because it sure would make it a lot easier to setup.   Just something simple like a simple light being controlled via mycroft and openhab would be great.  If not video is a there blog showing a step by step (type of thing) for getting it setup and running.   Thanks

**Comment by mortommy** [comment]
Hi,
I'm sorry, currently no video is available. Hope the [help documentation](https://www.openhab.org/docs/ecosystem/mycroft/) can make you work with the skill.
