### ISSUE TITLE
Please consider submitting the OpenHAB Skill to the 18.08 branch of mycroft-skills

### ISSUE THREAD

**Issue by KathyReid** [openhab/openhab-mycroft#54]
Hi there @mortommy, firstly we’d like to say a huge well done on the OpenHAB Skill. 

We’ve now moved `mycroft-skills` to the 18.08 branch, and we’d really love to have the OpenHAB Skill available on this branch. If your Skill was already accepted into the 18.02 branch, getting it on to the 18.08 branch is likely to be really simple and easy - simply a case of submitting it to the `mycroft-skills` repo again.

To make this easier, we now have the Mycroft Skills Kit - `msk` - available.

To open a PR on mycroft-skills, all your have to do is:

```bash
    cd <skill folder>
    mycroft-msk upload .
```

First, activate the virtual environment.

```
kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ source venv-activate.sh
Entering Mycroft virtual environment.  Run 'mycroft-venv-deactivate' to exit
Next, run msk upload with the path of where your Skill directory is locally.
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msk upload /path/to/where/your/skill/is/your-skill-name.username
```

For 18.08 we have a brand new Skill README editor, available at;
https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor.html

If your Skill is a straightforward resubmission, and just a README change, then we won’t put it through the full [Skill Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/) - we’ll just do a quick check to make sure everything’s shiny.

More information:
* [Skill branching](https://mycroft.ai/blog/skill-branching-18-02/)
* [What you need to know about the 18.08b branch](https://mycroft.ai/blog/18-08b-what-you-need-to-know-as-a-community-developer/)
* [Moving from Python 2.7 to Python 3.x](https://mycroft.ai/blog/python-2-7-python-3-4/)

We're also very happy to help assist with your Skill - find us in the [Skills Chatroom at Mycroft Chat](https://chat.mycroft.ai/community/channels/skills).

Kind regards,
Kathy

Mycroft AI

**Comment by mortommy** [comment]
Done.
Thank you.
