### ISSUE TITLE
openHABSkill - shutting down skill

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-mycroft#68]
Hi,

Installing openhab skill for mycroft running the following command fails: 

> msm install openhab

The system where mycroft is running in is Ubunty:

```NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
```

```
22:00:47.175 - mycroft.skills.core:load_skill:123 - INFO - ATTEMPTING TO LOAD SKILL: openhab-skill.openhab with ID openhab-skill.openhab
22:00:47.399 - mycroft.skills.core:config:551 - WARNING - self.config is deprecated.  Switch to using self.setting["whatever"] within your skill.
22:00:47.400 - mycroft.skills.core:config:553 - WARNING - Traceback:
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/maarten/mycroft-core/mycroft/skills/skill_manager.py", line 391, in run
    self._load_or_reload_skill(skill_path) or
  File "/home/maarten/mycroft-core/mycroft/skills/skill_manager.py", line 328, in _load_or_reload_skill
    BLACKLISTED_SKILLS)
  File "/home/maarten/mycroft-core/mycroft/skills/core.py", line 136, in load_skill
    skill = skill_module.create_skill()
  File "/opt/mycroft/skills/openhab-skill.openhab/__init__.py", line 371, in create_skill
    return openHABSkill()
  File "/opt/mycroft/skills/openhab-skill.openhab/__init__.py", line 43, in __init__
    self.url = "http://%s:%s/rest" % (self.config.get('host'), self.config.get('port'))

22:00:47.402 - mycroft.skills.core:config:551 - WARNING - self.config is deprecated.  Switch to using self.setting["whatever"] within your skill.
22:00:47.416 - mycroft.skills.core:config:553 - WARNING - Traceback:
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/maarten/mycroft-core/mycroft/skills/skill_manager.py", line 391, in run
    self._load_or_reload_skill(skill_path) or
  File "/home/maarten/mycroft-core/mycroft/skills/skill_manager.py", line 328, in _load_or_reload_skill
    BLACKLISTED_SKILLS)
  File "/home/maarten/mycroft-core/mycroft/skills/core.py", line 136, in load_skill
    skill = skill_module.create_skill()
  File "/opt/mycroft/skills/openhab-skill.openhab/__init__.py", line 371, in create_skill
    return openHABSkill()
  File "/opt/mycroft/skills/openhab-skill.openhab/__init__.py", line 43, in __init__
    self.url = "http://%s:%s/rest" % (self.config.get('host'), self.config.get('port'))

22:00:47.785 - openHABSkill - WARNING - Unsupported language for openHABSkill, shutting down skill.
22:00:47.850 - mycroft.skills.core:load_skill:152 - INFO - Loaded openhab-skill.openhab
```

Any suggestions?

Thanks,

Maarten

**Comment by grondl** [comment]
Hi Marteen,
The same thing happened to me and I made it work by replacing one line in the python code.  I was also having a second problem that you may experience also so I'll document both.  I'm using mycroft on a Raspberry Pi so  in my case the python code for the openHAB skill is in the directory "/opt/mycroft/skills/openhab-skill.openhab" and the file is "__init__.py"
Here is an excerpt of my modified file.  The comment lines starting with #lg are followed with the line I replaced or changed.  In the first case I hardcoded the IP and Port address of my openHab server and in the second case I added "en-us" to the supported languages - I also added a line that documents the language in the log file so a new language code would be printed and then could be added if that's what's preventing the skill from starting up ...
class openHABSkill(MycroftSkill):

	def __init__(self):
		super(openHABSkill, self).__init__(name="openHABSkill")

		#lg		self.url = "http://%s:%s/rest" % (self.config.get('host'), self.config.get('port'))
		self.url = "http://192.168.2.230:8080/rest"

		self.command_headers = {"Content-type": "text/plain"}

		self.polling_headers = {"Accept": "application/json"}

		self.lightingItemsDic = dict()
		self.switchableItemsDic = dict()
		self.currentTempItemsDic = dict()
		self.currentHumItemsDic = dict()
		#self.currentThermostatItemsDic = dict()
		self.targetTemperatureItemsDic = dict()
		#self.homekitHeatingCoolingModeDic = dict()

		self.getTaggedItems()

	def initialize(self):
		
		#lg added en-us to supported language
		supported_languages = ["en-US", "it-IT", "de-DE", "en-us"]
		self.log.warning("LG language for " + self.name + " is " + self.lang )

Modifications go in around  lines 44 and 62.
I realise this may not be the right way of dealing with this but it did get the skill working and I have now been able to toggle lights on and off and verbally adjust the brightness.   I did try the self.setting["whatever"] option that your debug text indicated but I didn't succeed in making a cleaner correction ... I'm not a proficient python coder and am quite new to both Picroft and OpenHAB !
Hope this helps,
Luc.

**Comment by mortommy** [comment]
fixed by removing the deprecated method.
