### ISSUE TITLE
Bogus 'Unsupported language' log message

### ISSUE THREAD

**Issue by FloatingBoater** [openhab/openhab-mycroft#75]
Hi,

After seeing several `Unsupported language` WARNING messages in the logs, I added a debug line and found a comparison value to be incorrect.

I suggest two manual chages to `__init__.py:
Line 73 - add `self.lang` value to the log text:
```
self.log.warning("Unsupported language " + self.lang + " for " + self.name + ", shutting down skill.")
```

For me this gave:
```
openHABSkill | Unsupported language en-us for openHABSkill, shutting down skill.
```

This exposed the issue - `supported_languages` are mixed case, so on line 69 change `"en-US"` to `"en-us"`.

Being a native English speaker, I don't know what other values are set for language, but wonder if they also should be `"de-de"` rather than `"de-DE"`.

Thanks!

**Comment by mortommy** [comment]
Merged. Thank you.
