### ISSUE TITLE
Openhab skill missing for mycroft 19.08

### ISSUE THREAD

**Issue by umglurf** [openhab/openhab-mycroft#76]
The skill does not seem to be added to 19.08 skill list, only 19.02

**Comment by MDAR** [comment]
I appear to have the same problem.

Today I installed the Master Branch of Mycroft onto my Ubuntu machine, I have tried instructing Mycroft to "Install openhab" by voice and in the console, but it only replies with **"I didn't find any skill named openhab"**

The version number for Mycroft is shown as 19.8.4

Searching the Mycroft Marketplace for openHAB doesn't return any skills either.


I did clone the Git, but adding the configuration text at the end of `mycroft.conf `caused Mycroft not to load.

**Comment by MDAR** [comment]
I've found this post and followed the instructions, as best I can.

https://community.mycroft.ai/t/solved-openhab-skill-not-working-after-upgrade/7285/7

Cloned the GIT openhab skill into the skills folder
replaced the `__init__.py` file

But when I restart Mycroft and use the `:skills `command in the the CLI, It shows openhab skill in red.

On the [openHAB binding page for Mycroft](https://www.openhab.org/docs/ecosystem/mycroft/), it suggests that I need to add the URL for the openHAB instance (which is obvious really), but what it doesn't say is Where exactly within the mycroft.conf file (or even which mycroft.conf file, I assumed the one in the configuration folder.

`~/mycroft-core/mycroft/configuration/mycroft.conf`

```
"openHABSkill": {
        "host": "openHAB server ip",
        "port": "openHAB server port"
      }
```
_Obviously I changed that to the correct details_



I placed the text block at the very end of the file and Mycroft refused to restart, stating lots of errors in the mycroft.conf file that were no where the edit I made.

So I moved the closing } to after the text I added, but still no better.

Can anyone suggest where that text block needs to go?

Many thanks,

Stuart

**Comment by umglurf** [comment]
Hi

There is only one error in ```__init__.py```, I've created a PR to fix this: https://github.com/openhab/openhab-mycroft/pull/78
You only need to clone the repo and apply this fix, then restart mycroft. The skill will then register itself and you can change settings at https://home.mycroft.ai/skills

**Comment by mortommy** [comment]
PR merged. Thank you.
I also applied for a PR to v19.08 mycroft repository.

**Comment by umglurf** [comment]
Great. @MDAR until the skill is available again in the markedplace. you only need to clone this repo, no need to edit any files. The skil will then register and you can edit the setting at https://home.mycroft.ai/skills

**Comment by MDAR** [comment]
@umglurf 
Hi

Thanks for the response :-)

When I use the :skills command in the CLI it shows the openhab-mycroft skill in RED.

![Screenshot from 2019-12-11 16-38-21](https://user-images.githubusercontent.com/10905891/70640922-afb56800-1c34-11ea-8e1c-0b2f048020a9.png)

Following your link to home.mycroft.ai/skills doesn't show the openHAB skill.

I have deleted the openhab-mycroft folder in Skills and cloned it again from GitHub, just in case I made an error.

I asked for a "Update Configuration" but the return was that "Nothing has changed"


The skill is still shown in Red, and there is no mention of openHAB on the home.mycroft.ai/skills page.

Is there anything else I can try?


**Update**

What I have found is an entry in the Skills.log which states that the openhab skill failed to load.

Does this make any sense to you?


What is "FuzzyWuzzy"???

Apart from a reference in one of my favourite films....


```
2019-12-11 16:50:53.426 | INFO     | 10349 | mycroft.skills.skill_loader:load:112 | ATTEMPTING TO LOAD SKILL: openhab-mycroft
2019-12-11 16:50:53.429 | ERROR    | 10349 | mycroft.skills.skill_loader:_load_skill_source:206 | Failed to load skill: openhab-mycroft (ModuleNotFoundError("No module named 'fuzzywuzzy'"))
Traceback (most recent call last):
  File "/root/mycroft-core/mycroft/skills/skill_loader.py", line 199, in _load_skill_source
    ('.py', 'rb', imp.PY_SOURCE)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mycroft/skills/openhab-mycroft/__init__.py", line 21, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'
2019-12-11 16:50:53.433 | ERROR    | 10349 | mycroft.skills.skill_loader:_communicate_load_status:277 | Skill openhab-mycroft failed to load

```

**Comment by umglurf** [comment]
Since you are installing the skill manually, mycroft does not install the required python modules for you. I didn't see this as I've installed the skill in the previous version of mycroft from the markedplace, and thus had the modules installed.
Go to the mycroft folder and run
```
. .venv/bin/active
pip install -r skills/openhab-mycroft/requirements.txt
```

**Comment by MDAR** [comment]
> Since you are installing the skill manually, mycroft does not install the required python modules for you. I didn't see this as I've installed the skill in the previous version of mycroft from the markedplace, and thus had the modules installed.
> Go to the mycroft folder and run
> 
> ```
> . .venv/bin/active
> pip install -r skills/openhab-mycroft/requirements.txt
> ```

Thanks for the great help, I really appreciate you taking the time,

I thought I had found something, thanks to your reply, but unfortunately it hasn't changed anything.

I don't know if it makes a difference, but I hadn't activated the Python virtual environment. (Not sure what that means)

So I ran this command

`source venv-activate.sh` 

Followed by your suggestion of

`pip install -r skills/openhab-mycroft/requirements.txt`

This failed, but this seemed to work

`pip3 install -r skills/openhab-mycroft/requirements.txt`

In so much as I clearly saw "fuzzywuzzy" being installed.

However, when I started Mycroft, this appeared in the log again..

```
2019-12-11 19:32:26.988 | INFO     |  6950 | mycroft.skills.skill_loader:load:112 | ATTEMPTING TO LOAD SKILL: openhab-mycroft
2019-12-11 19:32:26.990 | ERROR    |  6950 | mycroft.skills.skill_loader:_load_skill_source:206 | Failed to load skill: openhab-mycroft (ModuleNotFoundError("No module named 'fuzzywuzzy'"))
Traceback (most recent call last):
  File "/root/mycroft-core/mycroft/skills/skill_loader.py", line 199, in _load_skill_source
    ('.py', 'rb', imp.PY_SOURCE)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/mycroft/skills/openhab-mycroft/__init__.py", line 21, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'
2019-12-11 19:32:26.994 | ERROR    |  6950 | mycroft.skills.skill_loader:_communicate_load_status:277 | Skill openhab-mycroft failed to load

```

Just to be sure, while in the virtual environment, I ran this command again

`pip3 install -r skills/openhab-mycroft/requirements.txt`

Which returned this -

```
Requirement already satisfied: requests>=2.10.0 in ./.venv/lib/python3.7/site-packages (from -r skills/openhab-mycroft/requirements.txt (line 1)) (2.20.0)
Requirement already satisfied: fuzzywuzzy==0.14.0 in ./.venv/lib/python3.7/site-packages (from -r skills/openhab-mycroft/requirements.txt (line 2)) (0.14.0)
Requirement already satisfied: python-Levenshtein==0.12.0 in ./.venv/lib/python3.7/site-packages (from -r skills/openhab-mycroft/requirements.txt (line 3)) (0.12.0)
Requirement already satisfied: idna<2.8,>=2.5 in ./.venv/lib/python3.7/site-packages (from requests>=2.10.0->-r skills/openhab-mycroft/requirements.txt (line 1)) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.7/site-packages (from requests>=2.10.0->-r skills/openhab-mycroft/requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.venv/lib/python3.7/site-packages (from requests>=2.10.0->-r skills/openhab-mycroft/requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./.venv/lib/python3.7/site-packages (from requests>=2.10.0->-r skills/openhab-mycroft/requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: setuptools in ./.venv/lib/python3.7/site-packages (from python-Levenshtein==0.12.0->-r skills/openhab-mycroft/requirements.txt (line 3)) (42.0.2)
```

**Comment by MDAR** [comment]
Okay...

I'm not entirely sure what I've done, but I now have an openHAB Skill in the home.mycroft.ai/skills page

To which I modified the URL to point at the correct machine. (Just the IP address, without any slashes)

I think..

I forced a re-install of python2.7

then started the virtual environment for Mycroft

Ran the `pip install -r skills/openhab-mycroft/requirements.txt` command, which again said everything was present.

However, when I started Mycroft, it suddenly chirped up that it couldn't get the Items list, so I assumed this meant the openhab Items?

"list openhab items"

returned

"Found the following items"
and not a lot more.

So a quick
./stop-mycroft.sh

and 
./start-mycroft.sh all

then in the cli I asked 

refresh openhab items

which returned all 78 items :-)

I just had to listen to Mycroft reading out ever single one of them.....

**Comment by MDAR** [comment]
Now I just need to work out what the audio test sounds so terrible.
I think something is conflicting with the microphone.

But that's for another day and another thread.

@umglurf Thanks for all your help :+1: 
I would never have got this far without it

What I might well do, is try to load Mycroft onto the Odroid that is running openHAB and get to work connecting some kind of microphone and speaker....

**Comment by MDAR** [comment]
@umglurf 
Hi

I just saw this flash up in the log, does it mean we can't get colors / colours with Mycroft any longer?

And... what does "Unsupported language for openHABSkill" mean? (not that I'll really understand, as I'm certainly more of a Wires and Cables type of chap.)

```
2019-12-11 21:06:25.281 | WARNING  | 12411 | mycroft.skills.settings:_update_settings_meta:302 | DEPRECATION WARNING: The "color" attribute in the settingsmeta file is no longer supported.
2019-12-11 21:06:25.285 | WARNING  | 12411 | mycroft.skills.settings:_update_settings_meta:302 | DEPRECATION WARNING: The "name" attribute in the settingsmeta file is no longer supported.
2019-12-11 21:06:25.710 | INFO     | 12411 | mycroft.skills.skill_loader:load:112 | ATTEMPTING TO LOAD SKILL: openhab-mycroft
2019-12-11 21:06:25.723 | INFO     | 12411 | mycroft.skills.settings:get_local_settings:78 | /opt/mycroft/skills/openhab-mycroft/settings.json
2019-12-11 21:06:25.788 | WARNING  | 12411 | openHABSkill | Unsupported language for openHABSkill, shutting down skill.
2019-12-11 21:06:26.372 | INFO     | 12411 | mycroft.skills.skill_loader:_communicate_load_status:270 | Skill openhab-mycroft loaded successfully

```

**Comment by krisgesling** [comment]
Hi MDAR, it looks like you've made great progress.

The "color" and "name" that are no longer supported are entries in the settingsmeta. Previously you could define a colour and a name that differed from your Skill name for the Skill settings block, but this was removed. It doesn't relate to colour's within the OpenHAB Skill at all.

In terms of unsupported language, have you set your language in mycroft.conf to something other than `en-us`? We don't for example have an `en-uk` as yet. 

A few other tips/comments from scanning the above thread
- Instead of editing the `mycroft.conf` file directly I'd encourage use of our new [Configuration Manager](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/config-manager). It's still on the commandline but allows you to edit specific values, and validates the JSON reducing the number of things that can go wrong. Generally if your edits to `mycroft.conf` disappear, it's because there was some JSON syntax error.
- Mycroft officially supports Python 3.5-3.7 (3.8 seems to be fine too)
- Installing a Skill from Github using `mycroft-msm install https://github.com/author/skill-repo` should install the listed dependencies, if it's not please let us know.
- You can install Python packages to the Mycroft virtual environment using `mycroft-pip install xxxxx`

**Comment by mortommy** [comment]
The skill has been just added to the 19.08

**Comment by krisgesling** [comment]
Hey just a quick note that we're seeing a strange issue with the git reference which is currently causing the install to fail. Investigating at the moment, but for now please continue to install using:
`mycroft-msm -l install https://github.com/mortommy/openhab-mycroft`
