### ISSUE TITLE
Cannot Dim Light

### ISSUE THREAD

**Issue by tioui** [openhab/openhab-mycroft#86]
Hi,

I have a Dimmer working on Openhab2 and the latest openhab-mycroft skill. When I try to dim the light by saying "Hey Mycroft, dim the kitchen light", I have the following error.

```
00:02:27.727 | ERROR    |   795 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:798 | An error occurred while processing a request in open HAB Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/openhab-mycroft.openhab/__init__.py", line 250, in handle_dimmer_status_intent
    curBright = int(curBrightList[len(curBrightList)-1])
ValueError: invalid literal for int() with base 10: 'ON'
```

It seems like the skill try to use 'ON' as a int device status and the conversion failed.

**Comment by mortommy** [comment]
Hi. It's as you said. Can you share the openHAB item definition?

**Comment by tioui** [comment]
Here it is:
```
Switch Kitchen_light_voice "Kitchen light" ["Lighting"]{channel="mqtt:topic:0ad06555:mj_dimmer1_percentage"}
```

**Comment by mortommy** [comment]
I think the problem here is the item type. The Switch type can have only ON/OFF status, you should use the Dimmer type (https://www.openhab.org/docs/configuration/items.html#type)
Could you change it?
Anyway, the case should be better managed with a proper error message.

**Comment by tioui** [comment]
Sorry. It works now. Thanks a lot.
