### ISSUE TITLE
Using different languages

### ISSUE THREAD

**Issue by fgrassmann** [openhab/openhab-mycroft#88]
Using a language different from English seems to pose problems. If the command to switch something on or off is different from "on" and "off", the skill simply does not work. Example: In German, you would say "schalte ... ein". I changed the order in onoff_command.rx to respect this, but this only works when working with the cli client ("schalte ... on"), as "on" is not recognised. I also had to change __init__.py, beginning in line 211, to the following:

                        if (self.voc_match(command, "on") != True) and (self.voc_match(command, "off") != True):
                                self.speak_dialog('ErrorDialog')
                        else:
                                if (self.voc_match(command, "on")):
                                        command = "on"
                                if (self.voc_match(command, "off")):
                                        command = "off"

With these changes, it seems to work right now. I think the same problem could occur in other languages as well.

Edit: You have to add "on.voc" and "off.voc" to the language with appropriate content for this to work...

**Comment by mortommy** [comment]
Hi, thank you for your suggestion. Analyze the issue form the code you proposed it is not so easy. Could you provide a PR? I can make some tests.

**Comment by fgrassmann** [comment]
Am 07.04.20 um 17:38 schrieb mortommy:
>
> Hi, thank you for your suggestion. Analyze the issue form the code you 
> proposed it is not so easy. Could you provide a PR? I can make some tests.
>
I hope this worked, although I got a DCO error message... Which I cannot 
solve...

Yours,


Ferdinand Grassmann
