### ISSUE TITLE
mycroft configuration error on fresh install

### ISSUE THREAD

**Issue by bahmrockk** [openhab/openhab-mycroft#94]
Hello,

I'm not sure if this is already a known issue.
 - I have a blank mycroft installation on an arch linux (guide: https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/linux ).
 - Work validated.
 - I've installed the openhab-mycroft skill according to the readme into /opt/mycroft/skills (analogue to picroft)

When restarting mycroft I get the following error in the logs (line 104 is the error):
[skills.log](https://github.com/openhab/openhab-mycroft/files/4527936/skills.log)

Please disregard if this is an user error :)

Cheers!

**Comment by mortommy** [comment]
Hi,
the log says there's no [configuration](https://www.openhab.org/docs/ecosystem/mycroft/#skill-configuration).

**Comment by bahmrockk** [comment]
[mycroft.conf.txt](https://github.com/openhab/openhab-mycroft/files/4528169/mycroft.conf.txt)

What a reply speed Oo
Config is attached - language, listener, etc is working fine.
This is the configuraiton in ~/.mycroft/mycroft.conf

Running mycroft-config get openHABSkill results in:
{
  "host": "192.168.1.4",
  "port": "8080"
}

So, yes, the error says there's no configuration - but there seems to be one and I have no idea how to get the skill to acknowledge that :)

Thanks!

**Comment by bahmrockk** [comment]
Addition: If you have the impression that this is a local problem (which it sounds like) please disregard the report - I thought this might be connected to a mycroft update.

**Comment by mortommy** [comment]
Hi,
maybe something is missing here, it should be:

```
 "openHABSkill": {
        "host": "192.168.1.4",
        "port": "8080"
      }
```

**Comment by bahmrockk** [comment]
Hello,

TL'DR: Test shows that any local configurations are ignored on a fresh installation, the skill only uses the remote settings on home.mycroft.ai

---
As you can see in the config file that is exaclty what's in there.
I've retested the setup with a fresh picroft installation - there the configuration is even ignored and it always takes the configuration from home.mycroft.ai

With an arch installation I can't configure anything there though. Mycroft.ai says "unknown Platform" and the configuration options in "Skills" is empty for Openhab:

![image](https://user-images.githubusercontent.com/6319185/80275956-5599d880-86e5-11ea-9bfe-028762841bf2.png)

(Version 1 is the Raspberry Pi which can (only!) be configured via the web interface).
I suspect that the skill tries to fetch the configuration from the remote system and as mycroft.ai doesn't provide one for this the above error occurs.

I also tested overwriting the remote configuration with a local one which doesn't work.
Apparently the skill at the Moment takes remote > rest.
IMO this is a bug as it should be the mycroft standard of user > system > remote > default configurations.
This behaviour is reproducable on a fresh installation of picroft and then installing the skill via your tutorial in the readme (only difference: The dependencies now need to be installed with mycroft-pip).

**Comment by mortommy** [comment]
Hi,
before to talk about bug, it is better to try to understand how everything work. The configuration management is not at skill level but at system level. As reported [here](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/config-manager) local configuration overwrites remote configuration and I think you could have basically two issues:
- wrong path of local configuration file. It is _mycroft-core/mycroft/configuration/mycroft.conf_ but in your post you typed _/.mycroft/mycroft.conf_
- missing skill name _"openHABSkill":_ in configuration

**Comment by bahmrockk** [comment]
Well I wrote of a bug as this happens with a blank picroft installation which made me suspect something is wrong on non-user side. As I seem to be wrong:
I'm closing this now as this seems to be a user error.

[edit] I just dont understand how mycroft-config get openHABSkill can return a valid result if it would be missing in the configuration - but me not understanding something doesn't mean it must be a bug[/edit]
[edit2] your link itself explains the user level on ~/.mycroft/mycroft.core which was the one I refered to[/edit2]
